import {
  IconDashboard,
  IconUsers,
  IconMegaphone,
  IconUser,
  IconInstagram,
  IconChart,
  IconWallet,
  IconGift,
  IconLifebuoy,
  IconAlertTriangle,
  IconShield,
  IconFileText,
  IconBell,
  IconSettings,
  IconLayers,
  type NavItem,
} from "@clip/ui";

// See docs/ui-ux/NAVIGATION_ARCHITECTURE.md "Admin (admin.domain.in)".
export const adminNav: NavItem[] = [
  { label: "Dashboard", href: "/dashboard", icon: <IconDashboard /> },
  {
    label: "User Management",
    href: "/users",
    icon: <IconUsers />,
    children: [
      { label: "All Users", href: "/users/all" },
      { label: "Brands", href: "/users/brands" },
      { label: "Clippers", href: "/users/clippers" },
      { label: "Admin Team", href: "/users/admin-team" },
      { label: "Suspended", href: "/users/suspended" },
    ],
  },
  {
    label: "Campaign Management",
    href: "/campaigns",
    icon: <IconMegaphone />,
    children: [
      { label: "All", href: "/campaigns/all" },
      { label: "Pending Approval", href: "/campaigns/pending-approval" },
      { label: "Active", href: "/campaigns/active" },
      { label: "Paused", href: "/campaigns/paused" },
      { label: "Completed", href: "/campaigns/completed" },
      { label: "Rejected", href: "/campaigns/rejected" },
    ],
  },
  {
    label: "Creator Management",
    href: "/clippers",
    icon: <IconUser />,
    children: [
      { label: "All Clippers", href: "/clippers/all" },
      { label: "Verification", href: "/clippers/verification" },
      { label: "Performance", href: "/clippers/performance" },
      { label: "Risk Review", href: "/clippers/risk-review" },
    ],
  },
  {
    label: "Instagram",
    href: "/instagram",
    icon: <IconInstagram />,
    children: [
      { label: "Connected Accounts", href: "/instagram/connected-accounts" },
      { label: "Connection Health", href: "/instagram/connection-health" },
      { label: "Errors", href: "/instagram/errors" },
    ],
  },
  {
    label: "Performance",
    href: "/performance",
    icon: <IconChart />,
    children: [
      { label: "Overview", href: "/performance/overview" },
      { label: "Metric Tracking", href: "/performance/metric-tracking" },
      { label: "Qualified Performance", href: "/performance/qualified-performance" },
      { label: "Suspicious Activity", href: "/performance/suspicious-activity" },
    ],
  },
  {
    label: "Finance",
    href: "/finance",
    icon: <IconWallet />,
    children: [
      { label: "Platform Wallet", href: "/finance/platform-wallet" },
      { label: "Payments", href: "/finance/payments" },
      { label: "Earnings", href: "/finance/earnings" },
      { label: "Withdrawals", href: "/finance/withdrawals" },
      { label: "Refunds", href: "/finance/refunds" },
      { label: "Transactions", href: "/finance/transactions" },
    ],
  },
  {
    label: "Referral System",
    href: "/referrals",
    icon: <IconGift />,
    children: [
      { label: "Overview", href: "/referrals/overview" },
      { label: "Referrals", href: "/referrals/list" },
      { label: "Rewards", href: "/referrals/rewards" },
      { label: "Rules", href: "/referrals/rules" },
    ],
  },
  { label: "Support", href: "/support", icon: <IconLifebuoy /> },
  { label: "Disputes", href: "/disputes", icon: <IconAlertTriangle /> },
  { label: "Content Moderation", href: "/moderation", icon: <IconLayers /> },
  { label: "Reports", href: "/reports", icon: <IconFileText /> },
  { label: "Notifications", href: "/notifications", icon: <IconBell /> },
  { label: "Settings", href: "/settings", icon: <IconSettings /> },
  {
    label: "Security",
    href: "/security",
    icon: <IconShield />,
    children: [
      { label: "Audit Logs", href: "/security/audit-logs" },
      { label: "Security Events", href: "/security/security-events" },
    ],
  },
];
